export const INITIALIZE_VIDEOS = "INITIALIZE_VIDEOS";
export const INITIALIZE_PLAYLISTS = "INITIALIZE_PLAYLISTS";
export const TOGGLE_PLAYLIST = "TOGGLE_PLAYLIST";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const UPDATE_PLAYLIST = "UPDATE_PLAYLIST";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const CLEAR_PLAYLIST = "CLEAR_PLAYLIST";
