export const SET_VIDEO_LIST = "SET_VIDEO_LIST";
export const TOGGLE_LIKE = "TOGGLE_LIKE";
export const ADD_NEW_PLAYLIST = "ADD_NEW_PLAYLIST";
export const TOGGLE_PLAYLIST = "TOGGLE_PLAYLIST";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const REMOVE_FROM_HISTORY = "REMOVE_FROM_HISTORY";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
